# Generated by Django 6.0.2 on 2026-02-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0003_ngo_created_at_alter_ngo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
