# Generated by Django 6.0.2 on 2026-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0004_alter_ngo_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
