# Generated by Django 6.0.2 on 2026-02-08 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_is_approved'),
        ('ngos', '0005_alter_ngo_is_approved'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteertask',
            name='volunteer',
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngos.ngo')),
                ('volunteer', models.ForeignKey(limit_choices_to={'role': 'volunteer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='VolunteerCampaign',
        ),
        migrations.DeleteModel(
            name='VolunteerProfile',
        ),
        migrations.DeleteModel(
            name='VolunteerTask',
        ),
    ]
