# Generated by Django 6.0.2 on 2026-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_volunteertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertask',
            name='impact_points',
            field=models.IntegerField(default=10),
        ),
    ]
