# Generated by Django 6.0.2 on 2026-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_campaign_alter_donation_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
