# Generated by Django 5.2.10 on 2026-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_amount', models.PositiveIntegerField()),
                ('raised_amount', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Poverty', 'Poverty'), ('Women', 'Women')], max_length=50)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
