# Generated by Django 5.2.10 on 2026-02-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('ngos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngos.ngo'),
        ),
    ]
