# Generated by Django 6.0.2 on 2026-02-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
