# Generated by Django 6.0.2 on 2026-02-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='impact_metric',
            field=models.CharField(default='Meals Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='impact_per_rupee',
            field=models.FloatField(default=0.02),
        ),
    ]
